api_platform:
    title: 'Cupidon'
    description: 'API Cupidon'
    version: '0.1'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        jsonld: ['application/ld+json']
        jsonhal: ['application/hal+json']
        json: ['application/json']
        multipart: ['multipart/form-data']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header

