vich_uploader:
    db_driver: orm

    mappings:
        graphic_style:
            uri_prefix: '%graphic_style_uri%'
            upload_destination: '%kernel.project_dir%/public%graphic_style_uri%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
