name: Continuous Deployment
on:
  push:
    branches:
      - develop
jobs:
  cd:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - name: Deploy from develop
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd ${{ secrets.SSH_DIRECTORY }}
            git pull origin develop
            DATABASE_URL=mysql://root:${{ secrets.DATABASE_PASSWORD }}@127.0.0.1:3306/cupidon?serverVersion=8.0 make deploy env=dev
            composer dump-autoload --no-dev --classmap-authoritative
            php bin/console c:c --env=prod
      - name: Setup Blackfire via setup-php Action
        uses: shivammathur/setup-php@v2
        with:
          extensions: blackfire, :xdebug
          tools: blackfire, blackfire-player
        env:
          BLACKFIRE_SERVER_ID: ${{ secrets.BLACKFIRE_SERVER_ID }}
          BLACKFIRE_SERVER_TOKEN: ${{ secrets.BLACKFIRE_SERVER_TOKEN }}
          BLACKFIRE_CLIENT_ID: ${{ secrets.BLACKFIRE_CLIENT_ID }}
          BLACKFIRE_CLIENT_TOKEN: ${{ secrets.BLACKFIRE_CLIENT_TOKEN }}
      - name: Profile
        run: blackfire-player run .blackfire.yaml --endpoint=https://cupidon-api.thomas-boileau.dev